name: Daily AWS Usage Tracker

on:
  schedule:
    - cron: "0 6 * * *" # Every day at 6 AM UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  track-usage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Make script executable
        run: chmod +x resourceUsageTracker/resourceTracker.sh

      - name: Run AWS usage tracker script
        run: ./resourceUsageTracker/resourceTracker.sh > resource_usage.log 2>&1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Nodemailer
        run: npm install nodemailer

      - name: Send email with results
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: node scripts/sendEmail.js

